
public enum AnomalyList 
{
   
    ChurnStretching,
    ChurnLeather,
    ChurnBleeding,
    BloodTrail,
    ExcessCups,
    CushionShadow,
    DatesVanishing,
    HairBraids,
    UnclearVoices,
    EyesOnFabric,
    NoReflection,
    MirrorFigure,
    FootprintsTrail,
    RababaWrongNote,
    CamelPeeking,
    ObjectsMultiply,
    ChestMoving,
    LanternColor,
    ObjectResize,
    ShadowOutside,
    CamelTwoHeaded,
    CamelTwistedLegs,
    CamelTaxidermy,
    CamelDeadBaby,
    SignWrongFigure,
    SignTurnBack,
    SignsMultiply,
    FaceInWell,
    SnakeRopes,
    WellBleeding,
    HandsFromWell,
    EyesFollow,
    ExcessFoxes,
    ShadowGrowing,
    OppositeShadow,
    TwinPlants,
    SkyPlanet,
    CurvedTrees,
    HollowTree,
    BloodyDoll,
    StepSound,
    DreamKiller,
    Camouflaged,
    MismatchedCreature,
    RandomCry


}
